#include "RNOH/PackageProvider.h"
#include "RNOHPackagesFactory.h"
#include "generated/RNOHGeneratedPackage.h"
#include "AsyncStoragePackage.h"
#include "SafeAreaViewPackage.h"
#include "RNLocalizePackage.h"

using namespace rnoh;

std::vector<std::shared_ptr<Package>> PackageProvider::getPackages(
    Package::Context ctx) {
  auto packages = createRNOHPackages(ctx); // <= autolinking
  packages.push_back(std::make_shared<RNOHGeneratedPackage>(
      ctx)); // generated by codegen-harmony v1 on app preBuilt stage)
  packages.push_back(std::make_shared<AsyncStoragePackage>(ctx));
  packages.push_back(std::make_shared<SafeAreaViewPackage>(ctx));
  packages.push_back(std::make_shared<RNLocalizePackage>(ctx));
  return packages;
}
